### ISSUE TITLE
PCSS 지원에 대해서

### ISSUE THREAD

**Issue by deepdarkvisitor** [Shell4026/ShellProtector#10]
PCSS가 릴툰과 포이요미 두개의 쉐이더를 지원하고 있습니다.
PCSS가 변환한 마테리얼은 정상적으로 프로텍터에 대응되지만
PCSS의 커스텀 프로퍼티가 변환과정에 날아가서 적용이 되지 않고 있습니다.
당연한 결과입니다만 혹시 PCSS의 지원 계획이 있으신지 이슈 남겨봅니다.

**Comment by Shell4026** [comment]
나중에 PCSS 셰이더를 다루게 된다면 고려해보겠습니다.
