### ISSUE TITLE
Incorrect Description of Parameter Multiplexing

### ISSUE THREAD

**Issue by C0D3-M4513R** [Shell4026/ShellProtector#11]
In the linked doc (https://github.com/seanedwards/vrc-worldobject/blob/main/docs/parameter-multiplexing.md) it states: 
> However, OSC updating multiple parameters is not atomic

Which is false according to [Osc Spec](https://opensoundcontrol.stanford.edu/spec-1_0.html):
>OSC Messages in the same OSC Bundle are atomic; their corresponding OSC Methods should be invoked in immediate succession as if no other processing took place between the OSC Method invocations.

Therefore a locking parameter should not be needed, if a proper implementation of the OSC app with OSC Bundles is made.

The issue is filed here, because the original has been archived.

**Comment by Shell4026** [comment]
I'm going to leave it locked for now, just in case there are any bugs in VRChat.
