### ISSUE TITLE
Optimization of the protector possible?

### ISSUE THREAD

**Issue by SquidNeko** [Shell4026/ShellProtector#14]
So when using the Shellprotect. My avatar becomes really laggy for people. Taking like 10-15 frames. Even more if they are close.
I have other friends also trying shellprotect on their avatars and same thing happening.

Why does shell protect makes avatars heavy? Performance drops ALOT sadly.
Been waiting with saying it, cause i wanted to be sure.

**Comment by Shell4026** [comment]
In my internal tests, it doesn't seem to be that performance heavy. Can you give us more information, such as the number of crypto materials or texture sizes?

**Comment by Shell4026** [comment]
Additionally, does it only lag when viewed up close?

**Comment by SquidNeko** [comment]
I dont know how to find this: crypto materials or texture sizes

However yes, everybody lags when viewing up close.
The closer someone is, even myself, the more laggy it becomes.

I have others that tried using Shellprotect and its the same problem for them too. Its laggy, but extremely laggy up close.

**Comment by Shell4026** [comment]
Which shader do you use, Poiyomi or liltoon?

'crypto materials or texture sizes' 
These are the materials and textures used in the encryption.

Let's see if I can make improvements based on that information.

**Comment by SquidNeko** [comment]
Im using Poiyomi and so were my other friends trying to use it too.
Texture sizes average 2K in size.
About 5 Materials.

**Comment by Shell4026** [comment]
What is the format of the texture compression: DXT1 or DXT5? Or are you using crunch compression?

You can click on a texture to view its information in the Inspector.

**Comment by SquidNeko** [comment]
![Screenshot 2024-06-30 094005](https://github.com/Shell4026/ShellProtector/assets/37712045/b7536ef2-6011-40ef-9466-bf5ad54bd0b3)

**Comment by Shell4026** [comment]
Does the same performance degradation occur when you change the texture filter from Bilinear to Point in the ShellProtector component? In this case, you may see staircasing in the texture, but it is lighter than when it is Bilinear.

If this is the case, I'll think about how I can optimize for Bilinear filters.

**Comment by SquidNeko** [comment]
Optimizing is wanted either way, cause i had to drop the Shellprotect for now because of the huge performance drops.

**Comment by Shell4026** [comment]
I've added some optimizations and options to help with optimization. I'm not sure if it will help.
