### ISSUE TITLE
Error in GetArrayDXT

### ISSUE THREAD

**Issue by cstria0106** [Shell4026/ShellProtector#16]
var segment = new ArraySegment<byte>(data, start, end); 라인에서 오류가 발생합니다.

더 자세히 말하자면 텍스쳐 임포트 설정이 다음과 같을 때 발생합니다

![image](https://github.com/user-attachments/assets/fdfd9d0f-9548-4fe4-aeb7-49fa7c7120f0)

저기서 Generate Mipmaps 옵션을 활성화할 경우 오류가 나지 않습니다.

![image](https://github.com/user-attachments/assets/2e0cbde8-44e0-45f5-8575-8059efc1e0b6)

**Comment by Shell4026** [comment]
해당 버그 원인을 못 찾고 있었는데 정말 감사합니다. 수정했습니다.
