### ISSUE TITLE
복호화 여부 확인하여 보이게 하는 기능

### ISSUE THREAD

**Issue by cstria0106** [Shell4026/ShellProtector#27]
원본 텍스쳐 해시와 현재 보여지는 텍스쳐의 해시를 비교하여 복호화 여부를 확인할 수 있으면
지금처럼 임의의 딜레이를 이용하는 fallback보다는 더 정확하게 할 수 있을 것 같은데
그런식으로 구현할 수 있을까요?

**Comment by Shell4026** [comment]
1. 해시를 비교하려면 스크립트를 사용해야 할 것 같은데, VRC에서 스크립트를 사용하지 못해서 불가능한 방법 같습니다.
2. 셰이더(GPU)에서 복호화 하기 때문에 CPU에서 복호화 된 텍스쳐의 해시를 비교할 수가 없습니다.

**Comment by cstria0106** [comment]
셰이더 내에서 복호화된 전체 텍스쳐에 대한 해시를 계산할 수는 없는건가요?

**Comment by Shell4026** [comment]
개별 픽셀의 해시 값만 알 수 있습니다.
