### ISSUE TITLE
Virus detected on newest OCS Zips

### ISSUE THREAD

**Issue by SquidNeko** [Shell4026/ShellProtector#28]
You may have an accidental virus in your OSC app and the other zip file.

https://www.virustotal.com/gui/file/a71dfb5309369d3c551a665cf32d630b61dfa16309bc9efaf6b803db83e880c6

**Comment by LycheeLilyBun** [comment]
I'm unable to download the OSC software because all my browsers are telling me the files have a virus and there's no way to ignore it and download the software anyways

**Comment by Shell4026** [comment]
Check out the zip file inside Unity's packages - shellprotect
This appears to be a misdiagnosis.

**Comment by Shell4026** [comment]
https://www.virustotal.com/gui/file/32f210fd21136e8da2c6ba21f086ddf85ea0ec27438bc1dccf7a93b40507b9af

I think I've figured out why. The problem was that after I fixed the code, I was building for 32-bit. I'll push it back up to 1.6.2, thanks for letting me know.

**Comment by SquidNeko** [comment]
No problem
