### ISSUE TITLE
몇 가지 문제가 있습니다.

### ISSUE THREAD

**Issue by deepdarkvisitor** [Shell4026/ShellProtector#8]
1. 1.84 버전 부터 릴툰(liltoon 1.4.0)에서 머티리얼이 렌더링 모드 투명한으로 설정되어 있으면 복호화가 되지 않습니다.
2. 1.9.0 버전에서 새롭게 지원하는 멀티 플렉싱모드가 제대로 작동을 하지 않는 것 같습니다.

**Comment by Shell4026** [comment]
1. 릴툰에서 서로 다른 텍스쳐 사이즈를 이용시 잘 안 되는 버그가 있었는데, 이걸 수정했습니다. 새 버전을 올려볼테니 한번 이걸로 해보시길 바랍니다.
2. OSC버전 1.3을 사용중이신가요? 새로 아바타를 업로드 해보시거나 C:\Users\유저\AppData\LocalLow\VRChat\VRChat\OSC 폴더를 지워보시길 바랍니다.

**Comment by deepdarkvisitor** [comment]
1. 1.9.1버전에서 복호화 되지 않던 버그가 해결되었습니다.
2. 해당 폴더를 지우니 멀티 플렉싱모드가 작동합니다. 감사합니다.
