### ISSUE TITLE
liltoon) 메인컬러 2nd 옵션이 켜져있으면 암호/복호가 제대로 되지 않습니다.

### ISSUE THREAD

**Issue by deepdarkvisitor** [Shell4026/ShellProtector#9]
쉐이더 : liltoon 1.4.0
메인컬러 / 알파 - 메인컬러2nd가 켜져있으면 암호/복호가 되지 않는 부분을 찾았습니다.
2nd를 끄고 암호화를 진행하니 정상적으로 복호화까지 됩니다.
의도가 된 부분인지 궁금합니다.

**Comment by Shell4026** [comment]
확인해보겠습니다.

**Comment by Shell4026** [comment]
메인컬러에 들어간 텍스쳐와 동일한 텍스쳐가 들어가 있으면 보안상의 이유로 자동으로 빠져버리게 돼있습니다. 현재 지원되는 암호화 텍스쳐는 메인컬러에 들어간 텍스쳐 뿐이므로 그런 것 같습니다. 예외로 림라이트, 아웃라인은 메인 텍스쳐와 같은 텍스쳐인 경우, 빠지지 않고 같이 암호화 됩니다.
